### ISSUE TITLE
No found file: 'addons/sourcemod/configs/FirePlayersStats/settings.ini'

### ISSUE THREAD

**Issue by 1nn7erplay** [OkyHp/Fire-Players-Stats#9]
L 02/12/2023 - 01:25:47: [SM] Exception reported: No found file: 'addons/sourcemod/configs/FirePlayersStats/settings.ini'.
L 02/12/2023 - 01:25:47: [SM] Blaming: FirePlayersStats.smx
L 02/12/2023 - 01:25:47: [SM] Call stack trace:
L 02/12/2023 - 01:25:47: [SM]   [0] SetFailState
L 02/12/2023 - 01:25:47: [SM]   [1] Line 51, FirePlayersStats/config.sp::LoadConfigKV
L 02/12/2023 - 01:25:47: [SM]   [2] Line 237, FirePlayersStats/config.sp::SetCvars
L 02/12/2023 - 01:25:47: [SM]   [3] Line 167, scripting/FirePlayersStats.sp::OnPluginStart
L 02/12/2023 - 01:25:47: [SM] Unable to load plugin "FirePlayersStats.smx": Error detected in plugin startup (see error logs)

**Comment by OkyHp** [comment]
No found file: 'addons/sourcemod/configs/FirePlayersStats/settings.ini'
